# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T14:21:42+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Eta(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class GravityAnomaly(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class Xi(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class Anomaly(BaseModel):
    eta: Optional[Eta] = Field(
        None, description='Eta (arcsec) - easterly component of deflection of vertical.'
    )
    gravity_anomaly: Optional[GravityAnomaly] = Field(
        None, description='Gravity anomaly (mGal)\n'
    )
    xi: Optional[Xi] = Field(
        None,
        description='Xi (arcsec) - northerly component of deflection of vertical.\n',
    )


class Height1(BaseModel):
    units: Optional[str] = None
    value: Optional[float] = None


class Height(BaseModel):
    height: Optional[Height1] = Field(None, description='Geoid height (m)\n')
